version: "3.9"

services:
  db:
    image: postgres:16
    container_name: storage_postgres
    restart: always
    environment:
      POSTGRES_USER: storageadmin
      POSTGRES_PASSWORD: storagepass
      POSTGRES_DB: storagedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: